### ISSUE TITLE
Does the CLOUDINARY_URL  environment variable work?

### ISSUE THREAD

**Issue by sethbrasile** [sethbrasile/ghost-cloudinary-store#1]
According to [this](http://cloudinary.com/documentation/node_additional_topics#configuration_options), it seems like you don't need to provide any config if you have this variable set.

Is this true?

If this is true, all that is needed in `config.js` is:

``` javascript
storage: {
    active: 'ghost-cloudinary-store'
}
```

Another question is: If this is true, does this module need to check for the env var's existence before setting it's config values, or will Cloudinary accept an empty config object and still work?

If no one else checks this out, I will when I get a chance :D

**Comment by ertrzyiks** [comment]
Just checked, its enough to set env variable CLOUDINARY_URL and use

```
storage: {
    active: 'ghost-cloudinary-store'
}
```

just like you said

**Comment by sethbrasile** [comment]
@ertrzyiks I'm having trouble with this. I have the environment variable set correctly but I'm getting `ERROR: Must supply api_key`

**Comment by jvrsgsty** [comment]
@sethbrasile I have been able to deploy Ghost on Heroku using the CLOUDINARY_URL variable exactly as explained in your documentation. 

Other than that, I am serving images using https, as described, no problems whatsoever.

```
storage: {
    active: 'ghost-cloudinary-store',
    'ghost-cloudinary-store': {
      secure: true
    }
}
```

**Comment by sethbrasile** [comment]
awesome! Thank you @jvrsgsty!
