### ISSUE TITLE
Breaking changes in Ghost 0.10.0

### ISSUE THREAD

**Issue by kirrg001** [sethbrasile/ghost-cloudinary-store#12]
Hey!

We will soon release Ghost `0.10.0` - in about 2 days.
It contains breaking changes for the storage adapter, see https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module.

**Comment by mmornati** [comment]
I updated the project for the 0.10.0. Waiting for the pull request to integrate it in the official release...

**Comment by mmornati** [comment]
Done. All is integrated and updated for Ghost 1.X version
