### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by pankajpatel** [sethbrasile/ghost-cloudinary-store#17]
Thank you for this ghost plugin/app.

I was going through installation process; but I wonder what would happen when there is a ghost update? Would this plugin require reinstallation? As after ghost update; the new version is downloaded and used which means the location `versions/$GHOST_VERSION/core/server/adapters/storage/` used while installing the plugin will not be useful any more.

**Comment by aphe** [comment]
i install ghost using ghost-cli, ghost create separated folder for content and ghost folder. so when ghost get updated, the content will not get replaced.

And also please consider to create issue [here](https://github.com/mmornati/ghost-cloudinary-store) since @sethbrasile rarely maintain this repo

**Comment by mmornati** [comment]
The folder you named is inside the Ghost installation. I'm using it cause on Docker I'm delivering the new ghost version with the okugin installed.
You can put the plugin in your content folder instead the version one and, as @aphe is saying, you will keep anything unchanged after any upload.
I can update the documentation with these instructions.

Thanks for the feedback.

**Comment by pankajpatel** [comment]
thanks @aphe @mmornati 
I think I was intending to ask that if it can be installed on different location i.e. content directory and made to work. I got the answers.

**Comment by mmornati** [comment]
Yes for sure. I will made some tests just to be sure to push the correct folder :)
The folder is **/ghost-override/content/adapters/storage/**
