### ISSUE TITLE
Custom favicon not working

### ISSUE THREAD

**Issue by evenfrost** [sethbrasile/ghost-cloudinary-store#18]
For reference: https://github.com/TryGhost/Ghost/issues/8771#issuecomment-331419119.

TL;DR: When adding a favicon to blog with `ghost-cloudinary-store`, it won't show on front end as `read` adapter method needs to be implemented for it to work.

**Comment by aphe** [comment]
i create the patch.

please review it 
```js

  read(options) {
      options = options || {};
      return new Promise(function (resolve, reject) {
          var request = require('request').defaults({ encoding: null });
          request.get(options.path, function (err, res, body) {
              if (err) {
                  reject(new Error("Cannot download image"))
              } else {
                  resolve(body)
              }
          });
      });
  }
```

i try and it works for my [case](https://github.com/TryGhost/Ghost/issues/8771#issuecomment-330737452) (i install using ghost-cli).

And also please consider to create issue [here](https://github.com/mmornati/ghost-cloudinary-store) since @sethbrasile rarely maintain this repo

**Comment by mmornati** [comment]
Thanks @aphe that's great. For your information I can now update this repo too. I will push changes on both too 'cause some peoples is using this one and some other the other one. But never mind.
I will check your changes and push them in the repo.

**Comment by mmornati** [comment]
@aphe is this change the read for the cloudinary plugin? If yes do you have a pull request?

**Comment by mmornati** [comment]
Just tested on my local environment and it seems with the @aphe patch is working good: I have the favicon and no error is shown.
I push this change to the repo.
Thanks @aphe
