### ISSUE TITLE
Ability to use https instead of the default http

### ISSUE THREAD

**Issue by sean-clayton** [sethbrasile/ghost-cloudinary-store#6]
https://github.com/sethbrasile/ghost-cloudinary-store/blob/master/index.js#L19

``` js
store.prototype.save = function(image) {
    return new Promise(function(resolve) {
        cloudinary.uploader.upload(image.path, function(result) {
            resolve(result.url);
        });
    });
};
```

If you could make it an option to get the https URL by changing the resolve from above to `resolve(result.secure_url)`, that'd be awesome. It should at least be the default, I think.

**Comment by sethbrasile** [comment]
Now supported with the `secure` option as of [1.1.0](https://github.com/sethbrasile/ghost-cloudinary-store/releases/tag/1.1.0). Closed by #5.

Thanks for the feedback @sean-clayton :+1:
