### ISSUE TITLE
Bitnami/Google Cloud 

### ISSUE THREAD

**Issue by peterluu** [sethbrasile/ghost-cloudinary-store#8]
I'm still trying to determine the exact problem, but wondering whether you might have come across this at all.

My Ghost installation is built on Bitnami/Google Cloud Platform.

```
[Sat Apr 30 02:51:00.482396 2016] [proxy:error] [pid 2488] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:2368 (127.0.0.1) failed
[Sat Apr 30 02:51:00.482427 2016] [proxy:error] [pid 2488] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s
[Sat Apr 30 02:51:00.482432 2016] [proxy_http:error] [pid 2488] [client 100.43.91.12:57906] AH01114: HTTP: failed to make connection to backend: 127.0.0.1
[Sat Apr 30 02:51:00.482644 2016] [proxy:error] [pid 2488] AH00940: HTTP: disabled connection for (127.0.0.1)
```

**Comment by sethbrasile** [comment]
I'm sorry @peterluu I didn't see a notification for this. 

Did you get it sorted?

**Comment by sethbrasile** [comment]
I am going to close this issue because it doesn't look related to cloudinary or ghost-cloudinary-store, but if you didn't get it sorted let me know, I'm still be glad to help.
