### ISSUE TITLE
Please correct the install instructions

### ISSUE THREAD

**Issue by ErisDS** [sethbrasile/ghost-cloudinary-store#9]
Hi there!

I have just done a review of all the modules that have been linked [here](https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module).

Your install instructions require users to do an `npm install --save` - this modifies the package.json and makes the upgrade path for Ghost much, much harder. This was never the intention with the storage system. 

Instead of `npm install --save`, please update your README and advise people to do the following:

`mkdir content/storage` (make the storage folder if it doesn't exist yet)
`cp node_modules/<module_name> content/storage/<module_name>` (copy the module into the right location)

That makes it much easier to upgrade Ghost in future. 

We are in the process of adding a cli tool that will do these steps automatically, so if your module isn't setup to work this way, it will need to be very soon 😉

**Comment by sethbrasile** [comment]
@ErisDS could you tell me if I revert to my previous installation instructions, if that would be acceptable? https://github.com/sethbrasile/ghost-cloudinary-store/commit/bb03efeccf2716376b26a239672c51629c2b2434

**Comment by ErisDS** [comment]
That would work, but it assumes that the user doesn't already have a `storage` folder. 

The instructions here have already been updated and can maybe be used for inspiration for something a little more straight forward:

https://github.com/wrenth04/ghost-imgur
https://github.com/tparnell8/ghost-azurestorage
https://github.com/Minwe/qn-store
